### ISSUE TITLE
v4.0 Release does not build

### ISSUE THREAD

**Issue by DL6AKU** [jedisct1/encpipe#1]
$ make
git submodule update --init
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make: *** [Makefile:29: ext/libhydrogen/hydrogen.c] Error 128

**Comment by DL6AKU** [comment]
Cloned from master it does build.

**Comment by sergeevabc** [comment]
Dear @jedisct1,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by sergeevabc** [comment]
Err… No Windows binary yet?
