### ISSUE TITLE
expected performance

### ISSUE THREAD

**Issue by digitalsignalperson** [jedisct1/encpipe#7]
Hey I was curious what performance to expect with this tool.

On a beefy PC I'm getting ~37MiB/sec with a 
`dd if=/dev/zero bs=1M count=1000 oflag=direct | encpipe -e -p testpass > /dev/null`

Is it a limitation of libhydrogen or the gimli implementation?

**Comment by jedisct1** [comment]
Hi!

It's not particularly meant to be fast. I really just wanted that tool to be compact, simple and reliable.

Maybe I'll do a super fast variant using libaegis, but in the meantime, encpipe has been protecting my backups for over 7 years, and for that kind of use case, performance was not the priority.

**Comment by digitalsignalperson** [comment]
Yeah totally appreciate the compact/simple/reliable. And cool to see libaegis as an option.

I'm also curious about the gimili permutation as something being simple but also potentially fast... [Gimli Encryption in 715.9 psec](https://eprint.iacr.org/2020/336.pdf) sounds like it has potential for competitive performance (though they mainly talk about latency not throughput, not sure how to interpret). Any thoughts on acceleration potential?

**Comment by jedisct1** [comment]
That paper is about hardware implementations; i.e. putting Gimli directly in a chip.

**Comment by digitalsignalperson** [comment]
ah oops, i feel dumb for scanning it and missing the point. thanks for the replies, I like the tool
